import images from "../../../assets/images";

const data = [

  {
    id: 1,
    image: images.anhdocument,
    title: "Nông nghiệp và nông dân",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "110",
    download: "20",
  },
  {
    id: 2,
    image: images.nongnghiephuuco,
    title: "Nông nghiệp hữu cơ là gì ?",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "210",
    download: "13",
  },
  {
    id: 3,
    image: images.tailieuhoinghi,
    title: "Tập huấn quản lý nhà nước gần với định hướng phát triển bền vững",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "152",
    download: "10",
  },
  {
    id: 4,
    image: images.yeutotamly,
    title: "Một số yếu tố tâm lý của nông dân",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "620",
    download: "220",
  },
  {
    id: 5,
    image: images.hoidapnongnghiep,
    title: "Hỏi đáp nông-lâm-ngư nghiệp",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "172",
    download: "19",
  },
  {
    id: 6,
    image: images.tailieutaphuan,
    title: "Sự phát triển của của mô hình phát triển nông nghiệp mới",
    content:
      "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
    eye: "20",
    download: "10",
  },
];

export default data;

    {
        id: 1,
        image : images.anhdocument,
        title: "Nông nghiệp và nông dân",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "110",
        download : "20",
    },
    {
        id: 2,
        image : images.nongnghiephuuco,
        title: "Nông nghiệp hữu cơ là gì ?",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "210",
        download : "13",
    },
    {
        id: 3,
        image : images.tailieuhoinghi,
        title: "Tập huấn quản lý nhà nước gần với định hướng phát triển bền vững",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "152",
        download : "10",
    },
    {
        id: 4,
        image : images.yeutotamly,
        title: "Một số yếu tố tâm lý của nông dân",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "620",
        download : "220",
    },
    {
        id: 5,
        image : images.hoidapnongnghiep,
        title: "Hỏi đáp nông-lâm-ngư nghiệp",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "172",
        download : "19",
    },
    {
        id: 6,
        image : images.tailieutaphuan,
        title: "Sự phát triển của của mô hình phát triển nông nghiệp mới",
        content: "Việt Nam được đánh giá là một trong những quốc gia sẽ bị ảnh hưởng nặng nề nhất bởi biến đổi khí hậu. Biến đổi khí hậu làm thay đổi cơ cấu mùa vụ, quy hoạch vùng, kỹ thuật tưới tiêu, sâu bệnh, năng suất, sản lượng; làm suy thoái tài nguyên đất, nước, đa dạng sinh học. Trong những năm qua, Ngành Nông nghiệp Việt Nam đã đạt được các thành tựu to lớn trong sản xuất nông sản phục vụ nội tiêu và xuất khẩu. Nhiều tiến bộ kỹ thuật trong lĩnh vực trồng trọt, bảo vệ thực vật, kỹ thuật tưới tiêu,... đã được nghiên cứu và áp dụng trong thực tiễn sản xuất, góp phần phát triển Ngành Nông nghiệp bền vững, hiệu quả, hạn chế thiệt hại do biến đổi khí hậu gây ra trong những năm gần đây. Sản xuất nông nghiệp thông minh thích ứng với biến đổi khí hậu (gọi tắt là CSA) - là một trong những giải pháp để giảm nhẹ sự tác động tiêu cực của biến đổi khí hậu. Tuy nhiên, hiện tại chưa có một tài liệu tổng hợp hướng dẫn thực hành CSA nào đối với từng cây trồng, bao gồm áp dụng tổng hợp các quy trình kỹ thuật canh tác như ICM, IPM, một phải năm giảm, ba giảm ba tăng, tưới khô ướt xen kẽ, tưới tiết kiệm,.... Từ năm 2014 - 2021, Bộ Nông nghiệp và Phát triển nông thôn đã triển khai Dự án Cải thiện nông nghiệp có tưới (VIAIP). Mục tiêu là nâng cao tính bền vững của hệ thống sản xuất nông nghiệp có tưới, trong đó Hợp phần 3 của Dự án đã hỗ trợ các tỉnh vùng Dự án thiết kế và thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu gồm: Áp dụng các gói kỹ thuật về sản xuất giống cây trồng, gói kỹ thuật canh tác, bảo vệ thực vật, đánh giá nhu cầu và áp dụng các phương pháp tưới tiên tiến nhằm nâng cao năng suất, chất lượng cây trồng; sử dụng nước tiết kiệm và tăng hiệu ích sử dụng nước; tăng thu nhập cho nông dân; giảm tính dễ tổn thương với biến đổi khí hậu, giảm phát thải khí nhà kính; tổ chức và liên kết sản xuất nông sản theo chuỗi giá trị gia tăng, giảm giá thành sản xuất, tăng lợi nhuận cho người dân. Cục Trồng trọt được Bộ Nông nghiệp và Phát triển nông thôn giao nhiệm vụ phối hợp với Ban Quản lý Trung ương Các dự án Thủy lợi và các tỉnh tham gia Dự án triển khai các nội dung liên quan đến nông nghiệp thông minh thích ứng với biến đổi khí hậu (CSA). Trên cơ sở tổng kết các kết quả, tài liệu liên quan, Cục Trồng trọt xin giới thiệu Bộ tài liệu “Sổ tay Hướng dẫn gói kỹ thuật canh tác thích ứng với biến đổi khí hậu cho một số cây trồng chủ lực như lúa, màu, rau, cây ăn quả có múi (cam, bưởi), chè, hồ tiêu, điều, cà phê, nhãn, vải, xoài, chuối, thanh long và sầu riêng”. Bộ tài liệu này được xây dựng trên cơ sở thu thập, phân tích, tổng hợp, chuẩn hóa các kỹ thuật canh tác, kỹ thuật tưới, tiêu nước, để hoàn thiện Quy trình thực hành nông nghiệp thông minh thích ứng với biến đổi khí hậu cho các cây trồng nhằm phổ biến đến các tổ chức, cá nhân và các địa phương tham khảo áp dụng rộng rãi trong sản xuất.",
        eye: "20",
        download : "10",
    },

    
];
  
  export default  data;

